ecommerce/djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import  static
from django.urls import include, path
from . import views
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name="djecommerce"

urlpatterns = [
    path('',HomeView.as_view(),name="home"),
    path("product/<slug>/",ItemDetailView.as_view(),name="product"),
    path("checkout",CheckoutView.as_view(),name="checkout"),
    path("add-to-cart/<slug>",views.add_to_cart,name="add_to_cart"),
    path("add-coupon/",AddCouponView.as_view(),name="add-coupon"),
    path("remove_from_cart/<slug>",views.remove_from_cart,name="remove_from_cart"),
    path("login",views.login_view,name="login_view"),
    path("logout",views.logout_view,name="logout_view"),
    path("signup",views.signup,name="signup"),
    path("order-summary/",OrderSummaryView.as_view(),name="order-summary"),
    path("remove_single_item_from_cart/<slug>",views.remove_single_item_from_cart,name="remove_single_item_from_cart"),
    path("payment/<payment_option>/",PaymentView.as_view(),name="payment"),
    path("request-refund/",RequestRefundView.as_view(),name="request-refund")
]

if  settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djecommerce/', include('djecommerce.urls'))
]

ecommerce/djecommerce/models.py
from re import A
from sqlite3 import Timestamp
from statistics import mode
from tabnanny import verbose
from django.urls import reverse
from secrets import choice
from django.db import models
from django.contrib.auth.models import AbstractUser
from .forms import COUNTRIES
CATEGORY_CHOICES =(
    ('S','Shirt'),
    ('SW','Sport wear'),
    ('OW','Out Wear')
)

LABEL_CHOICES =(
    ('P','primary'),
    ('S','secondary'),
    ('D','danger')
)

ADDRESS_CHOICES =(
    ('B','Billing'),
    ('S','Shipping')
)




# Create your models here.
class User(AbstractUser):
    pass


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True , null=True)
    category = models.CharField(max_length=2,choices=CATEGORY_CHOICES)
    label = models.CharField(max_length=1,choices=LABEL_CHOICES )
    slug = models.SlugField()
    image = models.ImageField(upload_to="images",blank=True,null=True)
    description = models.TextField()
    

    def get_image(self):
        
        media ="/Users/mohamed/Desktop/django-ecommerce1/django-ecommerce-real/ecommerce/media"
        return  media + "/" + f"{self.image}" 
    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("djecommerce:product",kwargs={
            "slug":self.slug
        })
    
    def get_add_to_cart(self):
        return  reverse("djecommerce:add_to_cart",kwargs={
            "slug":self.slug
        })
    
    def remove_from_cart(self):
        return reverse("djecommerce:remove_from_cart",kwargs={
            "slug":self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="orderitems")
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="orderitem")
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        
        return self.quantity * self.item.discount_price

    def  get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()


    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="order" )
    ref_code = models.CharField(max_length=20,blank=True ,null=True )
    ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    billing_address = models.ForeignKey("Address",related_name="billing_adress",on_delete=models.SET_NULL ,
        blank=True ,null=True)
    shipping_address = models.ForeignKey("Address",related_name="shipping_adress",on_delete=models.SET_NULL ,
        blank=True ,null=True)
    payment = models.ForeignKey("Payment",on_delete=models.SET_NULL ,
        blank=True ,null=True)
    coupon = models.ForeignKey("Coupon" ,on_delete=models.SET_NULL ,
        blank=True ,null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)


    """
    1.item added to cart
    2.add billing adress
    (Failed checkout)
    3.payment
    4. being develired
    5.Recevied
    6.refunds

    """


    def __str__(self):
        return f"{self.user.username}"

    def get_total_price(self):
        total = 0 
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total  -= self.coupon.amount
        return total 


class Address(models.Model):
    user = models.ForeignKey(User ,on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = models.CharField(max_length=2, choices=COUNTRIES)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1,choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.user.username}:{self.street_address}"
    class Meta:
        verbose_name_plural = "Adresses"

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(User , on_delete=models.SET_NULL , blank=True , null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return f"{self.user.username}"


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()


    def __str__(self):
        return f"{self.code}"


class Refund(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.id} {self.reason}"

ecommerce/djecommerce/views.py
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.core.exceptions import ObjectDoesNotExist
from .models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView , DetailView , View
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.contrib.auth import login as auth_login
from .forms import ChekoutForm, CouponForm, RefundForm
from django.contrib.auth.decorators import login_required
import stripe
import random 
import string 


def create_ref_code():
    return "".join(random.choices(string.ascii_lowercase+string.digits , k=20))


# Create your views here.

class HomeView(ListView):
    model = Item
    template_name = "home.html"
    paginate_by =10

class ItemDetailView(DetailView):
    model=Item
    template_name="product.html"


def is_valid_form(values):
    valid =True
    for field in values:
        if field == '':
            valid=False
    return valid


class OrderSummaryView(LoginRequiredMixin ,View):
    def get(self  ,*args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user , ordered=False)
            context = {
                "object":order
            }
            return render(self.request,"order_summary.html",context)
        except ObjectDoesNotExist:
            messages.info(self.request,"You don't have active order")
            return redirect("djecommerce:home")
    
    

def home(request):
    context = {
        "items":Item.objects.all()
    }
    return render(request,"home.html",context)

def product(request):
    context={
        "items":Item.objects.all()
    }
    return render(request,"product.html")


class CheckoutView(View):
    def get(self , *args, **kwargs):
        #form
        try:
            order = Order.objects.get(user = self.request.user , ordered=False)
            form = ChekoutForm()
            context = {
                "form":form,
                "order":order,
                "couponform":CouponForm(),
                "DISPLAY_COUPON_FORM":True
            }
            # print("1")
            try:
                print("search for shipping address")
                shipping_address_qs = Address.objects.filter(
                        user = self.request.user , 
                        address_type = 'S',
                        default = True
                        ).all()[0]
            except:
                shipping_address_qs =None
            print("finshish search for shipping address")
            print("if search address exist")
            if shipping_address_qs:
                print(" start search for shipping address")
                context.update({"default_shipping_address":shipping_address_qs})
                
                # 
            # except:
            shipping_address_qs=None
            try:
                billing_address_qs = Address.objects.filter(
                    user = self.request.user , 
                    address_type = 'B',
                    default = True
                    )[0]
                # print("1")
                if billing_address_qs:
                    context.update({"default_billing_address":billing_address_qs})
                    # print("1")
            except:
                billing_address_qs=None
            return render(self.request,"checkout.html",context)
        except ObjectDoesNotExist :
            messages.info(self.request,"you do not have an active order")
            return redirect("djecommerce:order-summary")

    def post(self,*args, **kwargs):
        form = ChekoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user , ordered=False)
            if form.is_valid():
            
                use_default_shipping = form.cleaned_data.get("use_default_shipping")
                if use_default_shipping:
                    # print("Using default shipping adress")
                    address_qs = Address.objects.filter(
                    user = self.request.user , 
                    address_type = 'S',
                    default = True
                    )
                    if address_qs:
                        shipping_address = address_qs[0]
                        order.shipping_address = shipping_address
                        order.save()
                    else:
                        messages.info(self.request,"No default shipping address available")
                        return redirect("djecommerce:checkout")
                else:
                
                    shipping_address1 = form.cleaned_data.get("shipping_address")
                    shipping_address2=form.cleaned_data.get("shipping_address2")
                    shipping_country = form.cleaned_data.get("shipping_country")
                    shipping_zip = form.cleaned_data.get("shipping_zip")
                    
                    if is_valid_form([shipping_address1,shipping_country,shipping_zip]):

                        shipping_address =Address(
                            user = self.request.user,
                            street_address = shipping_address1,
                            apartment_address = shipping_address2,
                            country = shipping_country,
                            zip = shipping_zip,
                            address_type = "S"
                        )
                        print(form.cleaned_data)
                        print("this form is valid")
                        shipping_address.save()
                        order.shipping_address = shipping_address
                        order.save()
                        set_default_shipping = form.cleaned_data.get("set_default_shipping")
                        if set_default_shipping:
                            shipping_address.default = True
                            shipping_address.save()

                    else:
                        messages.info(self.request,"Please fill in the required shipping address fields")
                        return redirect("djecommerce:checkout")

                use_default_billing = form.cleaned_data.get("use_default_billing")
                same_billing_address = form.cleaned_data.get("same_billing_address")
                
                if same_billing_address:
                    billing_address = shipping_address
                    billing_address.pk = None
                    billing_address.save()
                    billing_address.address_type = "B"
                    billing_address.save()
                    order.billing_address = billing_address
                    order.save()

                elif use_default_billing:
                    # print("Using default shipping adress")
                    address_qs = Address.objects.filter(
                    user = self.request.user , 
                    address_type = 'B',
                    default = True
                    )
                    if address_qs:
                        billing_address = address_qs[0]
                        order.billing_address = billing_address
                        order.save()
                    else:
                        messages.info(self.request,"No default billing address available")
                        return redirect("djecommerce:checkout")
                else:
                    # print("User is entering new billing address")
                    billing_address1 = form.cleaned_data.get("billing_address")
                    billing_address2=form.cleaned_data.get("billing_address2")
                    billing_country = form.cleaned_data.get("billing_country")
                    billing_zip = form.cleaned_data.get("billing_zip")
                    
                    if is_valid_form([billing_address1,billing_country,billing_zip]):

                        billing_address =Address(
                            user = self.request.user,
                            street_address = billing_address1,
                            apartment_address = billing_address2,
                            country = billing_country,
                            zip = billing_zip,
                            address_type = "B"
                        )
                        # print(form.cleaned_data)
                        # print("this form is valid")
                        billing_address.save()
                        order.billing_address = billing_address
                        order.save()
                        set_default_billing = form.cleaned_data.get("set_default_billing")
                        if set_default_billing:
                            billing_address.default = True
                            billing_address.save()

                    else:
                        messages.info(self.request,"Please fill in the required Billing  address fields")
                        return redirect("djecommerce:checkout")
                    
                    

                payment_option = form.cleaned_data.get("payment_option")
                # TODO: add redirect to the selected payment option
                if payment_option =="S":
                    return redirect("djecommerce:payment",payment_option="stripe")
                elif payment_option =="P":
                    return redirect("djecommerce:payment",payment_option="paypal")
                else:
                    messages.info(self.request,"Inavalid payment option")
                    return redirect("djecommerce:checkout")

        except ObjectDoesNotExist:
            messages.info(self.request,"You don't have active order")

ecommerce/djecommerce/templates/home.html
{% extends 'base.html' %}
{% load static%}

{% block head_title %}Sherif E-commerce {% endblock %}



{% block content %}

  

  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Sherif E-commerce</strong>
              </h1>

              <p>
                <strong>Ecommerce isn't the cherry on the cake, it's the new cake</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive E-commerce for the online shopping . Loved by over 500 000 users across the world
                  available. Create your own world</strong>
              </p>

              <button target="_blank" href="#" class="btn btn-outline-white btn-lg">
                  Discounts up to 40%
                
              </button>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Sherif E-commerce</strong>
              </h1>

              <p>
                <strong>Ecommerce isn't the cherry on the cake, it's the new cake</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive E-commerce for the online shopping . Loved by over 500 000 users across the world
                  available. Create your own world</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">
                Discounts up to 40%
              
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Sherif E-commerce</strong>
              </h1>

              <p>
                <strong>Ecommerce isn't the cherry on the cake, it's the new cake</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive E-commerce for the online shopping . Loved by over 500 000 users across the world
                  available. Create your own world</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">
                Discounts up to 40%
                
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          
          {% for item in object_list%}
          <!--Grid column-->
          
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            
            <div class="card">
              
              <!--Card image-->
              <div class="view overlay">
                <img src="/djecommerce{{item.image.url}}" class="card-img-top" alt="product">
                  <a href="{{item.get_absolute_url}}" >
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{item.get_category_display}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{item.get_absolute_url}}" class="dark-grey-text">{{ item.title}}
                      
                      <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
                      
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>
                    {% if item.discount_price%}
                     {{item.discount_price}}$
                     {% else %}
                      {{item.price}}
                     {% endif%}
                  </strong>
                </h4>

              </div>
              <!--Card content-->
              
            </div>
            <!--Card-->
          
          </div>
          <!--Grid column-->
        
          {% endfor %}

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">


          <!--Arrow left-->
          {% if page_obj.has_previous%}
          <li class="page-item ">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif%}
          <li class="page-item active">
            <a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif%}
        </ul>
      </nav>
      {% endif%}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->

  {% endblock content %}

ecommerce/djecommerce/templates/navbar.html
{% load cart_template_tag %}
<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'djecommerce:home'%}" target="_blank">
        <strong class="blue-text">Sherif E-commerce</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'djecommerce:home'%}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% if request.user.is_authenticated%}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{%url 'djecommerce:checkout'%}" target="_blank">Checkout</a>
          </li>
          {%endif%}
          
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">


          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'djecommerce:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{request.user|cart_item_count}} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'djecommerce:request-refund' %}" class="nav-link waves-effect">
              <span class="clearfix d-none d-sm-inline-block">Refund Requests </span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'djecommerce:logout_view' %}" class="nav-link waves-effect">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>

          {% else%}

          <li class="nav-item">
            <a href="{% url 'djecommerce:login_view' %}" class="nav-link waves-effect">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'djecommerce:signup' %}" class="nav-link waves-effect">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>

          {% endif%}


          <li class="nav-item">
            <a href="https://www.facebook.com/sherif.ronadlo" class="nav-link waves-effect" target="_blank">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          
          </li>
          <li class="nav-item">
            <a href="https://github.com/sherifgowaied" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              <i class="fab fa-github mr-2"></i>Sherif's GitHub
            </a>
          </li>
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

ecommerce/djecommerce/templates/request_refund.html
{% extends 'base.html' %}
{% load static%}

{% block head_title %}Sherif E-commerce {% endblock %}



{% block content %}

  


  <!--Main layout-->
  <main>
    <div class="container">

      <h2>Request Refund </h2>
    <form action="{% url 'djecommerce:request-refund' %}" method="post">
        {% csrf_token %}
        
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Ref code</label>
            {% comment %} <input type="password" class="form-control" id="exampleInputPassword1"> {% endcomment %}
            {{form.ref_code}}
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Message</label>
            {% comment %} <textarea class="form-control" id="exampleInputPassword1"></textarea> {% endcomment %}
            {{form.message}}
          </div>
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            {% comment %} <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"> {% endcomment %}
            {{form.email}}
            
          </div>
          
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
            
          </div>
      

      
    </div>
  </main>
  <!--Main layout-->

  {% endblock content %}